
name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-latest
          triplet: "x64-linux"
          compiler: g++-9
        - os: windows-latest
          triplet: "x64-windows"

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install (gcc-9) (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "CXX=${{ matrix.config.compiler }}" >> $GITHUB_ENV
    - name: vcpkg
      shell: bash
      run: |
        pwd
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install uwebsockets:${{ matrix.config.triplet }} cxxopts:${{ matrix.config.triplet }}
    - name: check vcpkg
      run: |
        cd vcpkg
        ./vcpkg list
    - name: cmake
      run: cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=${{ matrix.config.triplet }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=Artifact
    - name: build
      run: cmake --build . --config Release
    - uses: actions/upload-artifact@v1
      with:
        name: http-server-${{ matrix.config.triplet }}
        path: Artifact
